[workspace]

members = [
    "lib/pin_experiment",
    "lib/async_blocking",
    "lib/play_scope_thread",
    "lib/play_stream",
    "lib/play_any",
    "lib/tokio_select",
    "lib/channel_async",
    "play_arrow_flight",
]